### ISSUE TITLE
Spiders drop nothing on death

### ISSUE THREAD

**Issue by UltrascatterRED** [TheCyberBrick/Spiders-2.0#18] opened 2020-10-07 22:19 UTC
I've been playing on 1.16.3 with the mod installed for a bit, and I've found that the spiders do not drop anything in survival, not even XP orbs.

**Comment by TheCyberBrick** [comment] 2020-10-08 06:58
Are you sure about the loot not dropping? They use the regular spider loot tables, and I'm pretty sure the loot drops worked for me.
You're right about the XP though, I forgot to add that.

**Comment by UltrascatterRED** [comment] 2020-10-09 19:40
I killed four spiders in melee combat, and none of them even dropped spider eyes, which are supposed to be a guaranteed drop under those conditions, if I'm not mistaken. I could take another look though, maybe they did drop and I'm just blind.

**Comment by TheCyberBrick** [comment] 2020-10-16 16:59
I can't reproduce this. I think you're mistaken about the guaranteed drop according to my experience and the MC wiki:
> Upon death, a spider drops:
0–2 String. The maximum is increased by 1 per level of Looting, for 0-5 string with Looting III.
5 when killed by a player or tamed wolf.
A 1⁄3 chance of dropping a spider eye when killed by a player or tamed wolf. The maximum amount of spider eyes is increased by 1 per level of Looting. The chance of a spider not dropping any spider eyes can be found using the formula 2 / (Looting Level + 3). For example, Looting III gives a 1⁄3 chance of not dropping any spider eyes. All other amounts have an equal chance of occurring.

**Comment by TheCyberBrick** [comment] 2020-10-16 16:59
The XP drops are now fixed though 👍

**Closed as completed by TheCyberBrick** 2020-10-16 16:59 UTC
Labels: bug
